apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-headers
  namespace: admin-tools
data:
  X-Forwarded-Proto: "https"
  X-Forwarded-Port: "443"
  X-Forwarded-SSL: "on"
  X-Forwarded-For: "$proxy_add_x_forwarded_for"
  X-Frame-Options: "SAMEORIGIN"

